name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu_latest
    steps:
      - name: Simple JS Action
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: Erik